
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '186FD2188BBACEFC02892D05F34D58AE'
    
_lr_action_items = {')':([1,3,5,7,9,10,11,],[-2,-4,-6,10,-1,-3,-5,]),'(':([0,2,6,8,],[2,2,2,2,]),'+':([1,3,5,10,11,],[6,-4,-6,-3,-5,]),'*':([3,5,10,],[-4,8,-3,]),'NUM':([0,2,6,8,],[3,3,3,3,]),'$end':([1,3,4,5,9,10,11,],[-2,-4,0,-6,-1,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,6,],[4,7,9,]),'term':([0,2,6,8,],[1,1,1,11,]),'factor':([0,2,6,8,],[5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> term + expr','expr',3,'p_expr_a','Small Project 3.py',67),
  ('expr -> term','expr',1,'p_expr_b','Small Project 3.py',74),
  ('factor -> ( expr )','factor',3,'p_factor_a','Small Project 3.py',78),
  ('factor -> NUM','factor',1,'p_factor_b','Small Project 3.py',82),
  ('term -> factor * term','term',3,'p_term_a','Small Project 3.py',87),
  ('term -> factor','term',1,'p_term_b','Small Project 3.py',95),
]
